version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ server
      - "15672:15672"  # RabbitMQ interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  flask-app:
    build: .
    ports:
      - "13308:5001"
    environment:
      - FLASK_ENV=development
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - rabbitmq
      - mongo
  
  celery-worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info # app : celery_app이 위치한 파일 경로
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - rabbitmq
      - flask-app
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:5.0.17-ubuntu2004
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0"]

volumes:
  mongo_data:
