version: '3.9'

services:
  smartfarm-arduino:
    build: .
    ports:
      - "13308:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:5.0.17-ubuntu2004
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0"]

volumes:
  mongo_data:
